- message: "$author"
  color: "green"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions >= 500"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 200 && $additions < 500"

- label: "PR Size"
  message: "Small"
  color: "green"
  when: "$additions <= 200"

- label: "Waiting for"
  message: "QA"
  color: yellow
  when: "$payload.pull_request.body.includes('- [ ] QA')"

- label: "Passed"
  message: "QA"
  color: green
  when: "$payload.pull_request.body.includes('- [x] QA')"

- label: "Error"
  message: "Wrong target branch"
  color: "red"
  when: "$targetBranchName != 'main'"

- imageUrl: "https://api.qrserver.com/v1/create-qr-code/?size=50x50&data=https://pr-$prNumber.company.com"
  url: "https://pr-$prNumber.company.com"

- message: "Work in Progress"
  color: "yellow"
  when: "$payload.pull_request.title.includes('WIP')"

- label: "Warn"
  message: "Unchecked Tasks"
  color: "yellow"
  when: "$payload.pull_request.body.includes('- [ ]')"

- label: "Warn"
  message: "Missing labels"
  color: yellow
  when: "$payload.pull_request.labels.length === 0"

- label: "Warn"
  message: "Description is missing"
  color: "yellow"
  when: "$payload.pull_request.body == '' || $payload.pull_request.body == null"

- message: "Outside contributor"
  color: "#000000"
  when: "$payload.pull_request.author_association == 'NONE'"

- message: "First time contributor"
  color: "#000000"
  when: "$payload.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'"

- message: "New GitHub user"
  color: "#000000"
  when: "$payload.pull_request.author_association == 'FIRST_TIMER'"

- message: "Contributor"
  color: "#000000"
  when: "$payload.pull_request.author_association == 'CONTRIBUTOR'"

- label: "Label"
  message: "Bug"
  when: "$labels.includes('bug')"

- label: "Label"
  message: "Documentation"
  when: "$labels.includes('documentation')"

- label: "Label"
  message: "Duplicate"
  when: "$labels.includes('duplicate')"

- label: "Label"
  message: "Enhancement"
  when: "$labels.includes('enhancement')"

- label: "Label"
  message: "Good first issue"
  when: "$labels.includes('good first issue')"

- label: "Label"
  message: "Help wanted"
  when: "$labels.includes('help wanted')"

- label: "Label"
  message: "Invalid"
  when: "$labels.includes('invalid')"

- label: "Label"
  message: "Question"
  when: "$labels.includes('question')"

- label: "Label"
  message: "Wontfix"
  when: "$labels.includes('wontfix')"
